### ISSUE TITLE
RSchema.validate should exist

### ISSUE THREAD

**Issue by mordocai** [tomdalling/rschema#3]
An RSchema.validate that does not raise an exception on error like RSchema.validate! does should exist.

My first thought was that it should return true on success and false on error but that doesn't work very well since you would then have no way to get to the errors.

Perhaps it should return some kind of object that can be checked for success and contains the errors if there are any?

For now I wrote this really crappy wrapper for my own usecase:

    module RSchema
      def self.validate(*args)
        begin
          self.validate!(*args)
        rescue ValidationError
          return false
        end
        return true
      end
    end

If you know how this should be implemented I would be willing to do a pull request.

**Comment by tomdalling** [comment]
There is a non-throwing validation method called `validation_errors`, but if you want just a normal `validate` it's probably best to implement it in terms of `walk` something like this:

```ruby
def self.validate(schema, value)
  _, error = walk(schema, value)
  error.nil?
end
```

There is no `validate` method at the moment because if `validate` returns false, you have no way to get the error object. This may not be an issue, depending on how you're using the library, though.

**Comment by mordocai** [comment]
validation_errors might work for my use case, I'll take a look. Yeah, I agree that just returning false is a problem. 

Thanks for writing this by the way! Right now i'm just using it for my API tests but I plan on using it everywhere it makes sense.

**Comment by tomdalling** [comment]
No worries. Thanks!

**Comment by tomdalling** [comment]
As an update to this, I thought about it for a while, and I think a lot of people would expect a non-throwing method called `validate`. When they realise they want an error object instead of `false`, they can always switch to another method at that point. So, the `validate` method does exist in the current version of rschema, and it's just implemented as `validation_error(schema, value).nil?`.
